### ISSUE TITLE
This library works really well.

### ISSUE THREAD

**Issue by kobi** [dlclark/regexp2#12]
This is not an issue, I hope that's OK.
Someone pointed out regexp2 to me and I has to test it with one of [my test cases](https://kobikobi.wordpress.com/2013/07/06/solving-mazes-using-regular-expressions/), and it worked beautifully!
https://github.com/kobi/RecreationalRegex/blob/master/Go/RegexMaze.go
Thanks!

**Comment by dlclark** [comment]
Thanks for the feedback!

Obviously those maze-solving regex's are pretty advanced.  I appreciate any ideas you have to test and exercise edge cases (for bugs or performance) that you may have seen from other implementations.
