### ISSUE TITLE
Regexp is not working for following code. Could you please correct it , if the usage of "regexp2" library is wrong?

### ISSUE THREAD

**Issue by SaiSasankKhajjayam** [dlclark/regexp2#16]
package main

import (
		"fmt"
		"github.com/dlclark/regexp2"
)

func main() {
	re,_ := regexp2.Compile(`Deployment`, 0)
	fmt.Println(re.MatchString(`D.*`)) // ExpectedOutput: true , ActualOutput: false
	fmt.Println(re.MatchString(`D*`)) // ExpectedOutput: true , ActualOutput: false
	fmt.Println(re.MatchString(`Dep`)) // ExpectedOutput: true , ActualOutput: false
	fmt.Println(re.MatchString(`Deployment`)) // ExpectedOutput: true , ActualOutput: true
	
}

**Comment by hachi8833** [comment]
* The patterns and the target string are inverse.
* You should quote the string with `""`

```go
package main

import (
	"fmt"
	"github.com/dlclark/regexp2"
)

func main() {
	re, _ := regexp2.Compile("D.+nt", 0)
	fmt.Println(re.MatchString("Deployment")) // true
}
```

Well, I suggest you to avoid using `.*`; consider using `.+` first 😃
