### ISSUE TITLE
Valid regex doesn't compile

### ISSUE THREAD

**Issue by lozaericml** [dlclark/regexp2#20]
Hi!

If pattern contains `\_`, **regexp2** fails to compile it. Example:

```
_, err := regexp2.Compile("^/legacy/([\w|\d|\-\_]+)/([\w|\d|\-\_]+)/.*", 0)
if err != nil {
	fmt.Println(err)
}
```

Error is `error parsing regexp: unrecognized escape sequence \_ in ^/legacy/([\w|\d|\-\_]+)/([\w|\d|\-\_]+)/.*)`

This pattern works in **regexp** package.

thanks!

**Comment by dlclark** [comment]
Hello!  The `regexp2` engine matches the behavior of the C# regular expression engine and not all patterns that are valid for the Go stdlib `regexp` package are valid for `regexp2` (and vise versa).  This pattern gives the same error in the C# engine, so this is as-designed.

A couple notes on your pattern:
- escaping `_` is unnecessary
- `\w` includes `_` already, so you don't need to include it at all
- including pipes in a character group (`[]`) isn't needed each character (including escapes) is already in an OR automationlly.

I _think_ the pattern you want is: `^/legacy/([\w\d\-]+)/([\w\d\-]+)/.*`

Thanks,
Doug
