### ISSUE TITLE
Support ASCII Character Classes

### ISSUE THREAD

**Issue by johnschultz** [dlclark/regexp2#21]
Hi,

Thank you for the library. I needed negative lookbehinds and was disappointed to find them not supported in the standard Go `regexp` package.

In the course of converting some code over to use your package, I had to modify some of the regexes to use Perl character classes instead of the ASCII classes defined here: https://github.com/google/re2/wiki/Syntax

Example:  https://play.golang.org/p/MlCaJtyvQ7q

Copied below as well:
```
	re := regexp.MustCompile(`^[[:digit:]]+$`)
	if isMatch := re.MatchString(`12345667890`); isMatch {
		fmt.Println("Matched regexp")
	} else {
		fmt.Println("No Match regexp")
	}
	
	re2 := regexp2.MustCompile(`^[[:digit:]]+$`, 0)
	if isMatch, _ := re2.MatchString(`12345667890`); isMatch {
		fmt.Println("Matched regexp2")
	} else {
		fmt.Println("No Match regexp2")
	}
```

Output:
```
Matched regexp
No Match regexp2
```

It'd be nice to support these larger character classes as well to keep compatibility with the standard library's `regexp` package.

**Comment by dlclark** [comment]
Hello! I appreciate the idea here, but the main goal of the package is to maintain compatibility to the C# regexp engine (which doesn’t support the [[::]] syntax). If I add support as-is then technically valid regex’s would change behavior. 

 The only safe way I can imagine adding this is gated behind a compile option (RE2Compat or something).  There are several other changes that would increase compatibility with RE2 that could benefit from this option. 

I’ll poke at it and see the level of effort involved and let you know if it’s likely to happen.

**Comment by dlclark** [comment]
Check out 92c702a (v1.2.0) -- I've added an `regexp2.RE2` RegexOption to use when compiling your patterns that enables RE2-inspired syntax.  At this point it's just python-style named capture groups and named ascii char classes, but it's a start as things come up.  

Thanks for the suggestion and let me know if you find anything else when porting from the stdlib `regexp` package.
