### ISSUE TITLE
What are the valid values for RegexOptions?

### ISSUE THREAD

**Issue by Manaswi94** [dlclark/regexp2#22]
Compile method takes in regular expression and RegexOptions. https://godoc.org/github.com/dlclark/regexp2#Compile

I have checked the documentation  and I could not find valid values for `RegexOptions`.

Could some one please provide the values for `RegexOptions` or point me to the documentation where I can find it?

**Comment by jhngrant** [comment]
GoDoc:

https://godoc.org/github.com/dlclark/regexp2#pkg-constants

**Comment by Manaswi94** [comment]
@jhngrant Thank you.

**Comment by dlclark** [comment]
@dotslash-Gatsby yes, just "or" the options together: `regexp2.ECMAScript | regexp2.IgnoreCase` to enable both flags.
