### ISSUE TITLE
Seems to fail a positive lookahead

### ISSUE THREAD

**Issue by rafaelcn** [dlclark/regexp2#23]
Hello, I was checking it out and it seems to fail a regular expression. For a given text [like this one](https://pastebin.com/bCbcaqF8), the expression `((Art\.\s\d+)[\S\s]*?(?=Art\.\s\d+)) ` fails to match every Art. block in the text. I've tested the expression on [this website ](https://regexr.com/) and there it gives me the correct count of 12 matches. 

Am I missing something? Maybe a multiline flag?

**Comment by dlclark** [comment]
Hi @rafaelcn do you have sample code you can show?  I've made a test app with the given expression and inputs and it gives me 12 matches (with no options).

**Comment by rafaelcn** [comment]
Yes I do. 

```
re := regexp2.MustCompile(`((Art\.\s\d+)[\S\s]*?(?=Art\.\s\d+))`, 0)

if m, _ := re.FindStringMatch(string(content)); m != nil {
	log.Printf("(%d) %v", len(m.Groups()), m.String())

	for _, group := range groups {
		log.Printf("--> %s \n\n", group.String())
	}

}
```

**Comment by rafaelcn** [comment]
Would you care to give the code of the test app?

**Comment by dlclark** [comment]
The groups returned from `m.Groups()` are the sub-matches (things in parentheses) of the match itself.   To access all 12 matches you'll need to loop through them like this:

```golang
for m, _ := re.FindStringMatch(string(content)); m != nil; m, _ = re.FindNextMatch(m) {
  // m.String() is the text of the whole match
}
```

**Comment by rafaelcn** [comment]
Okay, understood. I was kindof looking at the metthod `FindNextMatch` with narrow eyes. :stuck_out_tongue_closed_eyes:

**Comment by dlclark** [comment]
Glad we got it worked out!

Unrelated: your pattern will also not capture the _last_ Article (number 13) -- because the string ends instead of having another Article.

**Comment by rafaelcn** [comment]
Yep, I'm aware of that but it doesn't matter that much because the last _article_ is not that important. I'm still in trouble here. not getting all the 12 matches as you told you got. Now I'm getting only seven

**Comment by rafaelcn** [comment]
Ops, forget what I wrote. I was looking at a different file!
