### ISSUE TITLE
\Z not work on regexp2.RE2 mode

### ISSUE THREAD

**Issue by yywing** [dlclark/regexp2#46]
```golang
s1  := `^Google\nApple$`
s2  := `^Google\nApple\Z`
data := "Google\nApple\n"
```

```
// will get result
re, err := regexp2.Compile(s, regexp2.Singleline)
// will not get result
re, err := regexp2.Compile(s, regexp2.Singleline|regexp2.RE2)
```

Why?

**Comment by dlclark** [comment]
This is because of #24. With `RE2` option in `Singleline` mode we change `\Z` and `$` to mean "End of String" -- so the extra `\n` at the end prevents a match (which matches the RE2 behavior).  The .NET engine behavior is a bit different and allows the trailing `\n`.
