### ISSUE TITLE
Compatibility issue with NKo Digits

### ISSUE THREAD

**Issue by tschaub** [dlclark/regexp2#47]
It looks like `\d` matches `߀` ([`\u07c0`](https://unicode-table.com/en/07C0/))  with regexp2, but not with the standard library regexp.

See the [following example](https://go.dev/play/p/CWVnPLBuuCU):
```go
package main

import (
	"fmt"
	"regexp"

	"github.com/dlclark/regexp2"
)

func main() {
	re := regexp.MustCompile(`^\d$`)
	re2 := regexp2.MustCompile(`^\d$`, regexp2.RE2)

	notZero := "߀" // \u07c0

	match := re.MatchString(notZero)
	fmt.Printf("regexp: %v\n", match)

	match2, _ := re2.MatchString(notZero)
	fmt.Printf("regexp2: %v\n", match2)
}
```

Perhaps this is a known issue, but I'm wondering if there is a way to get additional compatibility with the standard library.

**Comment by tschaub** [comment]
I missed the `regexp2.ECMAScript` option.  Looks like compiling with this option is what I'm after.  Thanks for the work on this library.

**Comment by dlclark** [comment]
No problem.  The `ECMAScript` option does change the character classes to match ECMAScript/JavaScript and it just so happens that ECMAScript `\d` and `\w` matches the same chars as Go's RE2 engine.  However, `\s` does not contain the exact same chars in RE2 and ECMAScript.  

It makes sense to use the RE2 char class definitions for all 6 (`\s` `\w` `\d` plus negates) if option `RE2` is used. Forcing the ECMAScript option isn't ideal.

Thanks for bringing it up.
