### ISSUE TITLE
Is it possible to get the name of the currently matched group?

### ISSUE THREAD

**Issue by dementedhedgehog** [dlclark/regexp2#53]
Say I have a regex to tokenize some language..

```
# in python.
regex = re.compile(
    "(?P<comment>#.*?$)|"
    "(?P<newline>\n)|"     # has to go ahead of the whitespace
    "(?P<comma>,)|"       
    "(?P<double_quote_string>\".*?\")|" 
    "(?P<single_quote_string>'.*?')|"   
    "(?P<whitespace>[ \t\r\f\v]+)|"    ... etc

```
Here you expect to get multiple matches for each group name when tokenizing a file and you want to keep the ordering of the tokens.

If I use the same approach using regexp2 can I go from match to group name?  E.g. how do I get the last matched group name for a match?  Is that possible?

**Comment by dlclark** [comment]
Each `Match` has a set of `Groups` and each `Group` has a list of `Captures` with the values captured. Can you provide some pseudo code of what you're trying to do?  I don't really understand.  

If you're trying to parse a programming language then I recommend using a lexer/tokenizer instead.

**Comment by dementedhedgehog** [comment]
I was trying to write a tokenizer.   What I wanted was to feed in src code and get a list of (group_name, token_value) out eventually.  I ended up using the builtin regex iirc.
