### ISSUE TITLE
Panic on 32bit architectures

### ISSUE THREAD

**Issue by alanhamlett** [dlclark/regexp2#60]
Getting a panic when trying to load a 64bit int on a 32bit machine at line:
https://github.com/dlclark/regexp2/blob/af93f4cd0e5264ebe4d0dd1c4752bf906ec14ca7/fastclock.go#L103

The godocs say to instead use [Int64.Load](https://pkg.go.dev/sync/atomic#Int64.Load).

**Comment by dlclark** [comment]
The Int64 struct is available in Go 1.19 or later. I’d rather not increment the version requirement that far ahead if it can be avoided. 

A few questions to kick off the research: 
- What architecture are you using? 
- What panic error are you getting?
- What version of Go?

**Comment by dop251** [comment]
It can be avoided by making sure all atomicTime values are 64-bit aligned on 32-bit architectures (see https://pkg.go.dev/sync/atomic#pkg-note-BUG)

**Comment by gandarez** [comment]
@dlclark it panics on `Windows x86` with Go `1.19.6`. We're rolling out a new version so we can get the panic message.

**Comment by gandarez** [comment]
The panic message is `unaligned 64-bit atomic operation`.

**Comment by alanhamlett** [comment]
And the stacktrace:

```
panic({0xf75140, 0x11b9720})
 /opt/hostedtoolcache/go/1.19.6/x64/src/runtime/panic.go:884 +0x1ba
runtime/internal/atomic.panicUnaligned()
 /opt/hostedtoolcache/go/1.19.6/x64/src/runtime/internal/atomic/unaligned.go:8 +0x2d
runtime/internal/atomic.Load64(0x15f353c)
 /opt/hostedtoolcache/go/1.19.6/x64/src/runtime/internal/atomic/atomic_386.s:225 +0x10
github.com/dlclark/regexp2.(*atomicTime).read(...)
 /home/runner/go/pkg/mod/github.com/dlclark/regexp2@v1.8.0/fastclock.go:103
github.com/dlclark/regexp2.makeDeadline(0xee6b280)
 /home/runner/go/pkg/mod/github.com/dlclark/regexp2@v1.8.0/fastclock.go:46 +0x34
github.com/dlclark/regexp2.(*runner).startTimeoutWatch(...)
 /home/runner/go/pkg/mod/github.com/dlclark/regexp2@v1.8.0/runner.go:1557
github.com/dlclark/regexp2.(*runner).scan(0x11c6e000, {0x11cf4000, 0x9de, 0xa00}, 0x0, 0x0, 0xee6b280)
 /home/runner/go/pkg/mod/github.com/dlclark/regexp2@v1.8.0/runner.go:121 +0xb9
github.com/dlclark/regexp2.(*Regexp).run(0x11e54a00, 0x0, 0x0, {0x11cf4000, 0x9de, 0xa00})
 /home/runner/go/pkg/mod/github.com/dlclark/regexp2@v1.8.0/runner.go:90 +0xdf
github.com/dlclark/regexp2.(*Regexp).FindRunesMatchStartingAt(...)
 /home/runner/go/pkg/mod/github.com/dlclark/regexp2@v1.8.0/regexp.go:188
github.com/alecthomas/chroma.matchRules({0x11cf4000, 0x9de, 0xa00}, 0x0, {0x11e4c0c0, 0xa, 0x10})
```

**Comment by gandarez** [comment]
We realized it also panicked on other Archs/OS like `linux` on `ARM`.

**Comment by dlclark** [comment]
Ok based on what @dop251 found it appears that the issue is that Atomic operations require 64-bit alignment on 32-bit architectures.  

I _think_ the culprit is that the `fastclock` has a `time.Time` before using `atomicTime`. Since `time.Time` ends with a pointer (which would only be 32 bits for x86) we'll get off our alignment.  To fix this I _think_ we can just add a spacer to the `fastclock` struct (in fastclock.go): 
```golang
type fastclock struct {
	// current and clockEnd can be read via atomic loads.
	// Reads and writes of other fields require mu to be held.
	mu sync.Mutex

	start time.Time // Time corresponding to fasttime(0)
	//spacer for x86 arch
	_        int
	current  atomicTime // Current time (approximate)
	clockEnd atomicTime // When clock updater is supposed to stop (>= any existing deadline)
	running  bool       // Is a clock updater running?
}```

Unfortunately I don't have a 32-bit test environment.  @gandarez @alanhamlett are you able to make the above change locally and check if it fixes the issue?

**Comment by dop251** [comment]
Moving `current` and `clockEnd` to the beginning of the struct would work too and would not waste any space.

Also, if your environment supports running 32-bit executables (such as Linux or MacOS X 10.14 or earlier) you can reproduce it by running `GOARCH=386 go test -run TestDeadline`

**Comment by dlclark** [comment]
Reformatting the struct makes sense to me (instead of a spacer).  Sadly, I only have shiny new MacOS here so I can't test 32-bit stuff at all.

Anybody else able to give this a run in 32-bit to see if it works before I just cross my fingers and commit a new version?

```golang
type fastclock struct {
	current  atomicTime // Current time (approximate)
	clockEnd atomicTime // When clock updater is supposed to stop (>= any existing deadline)

	// current and clockEnd can be read via atomic loads.
	// Reads and writes of other fields require mu to be held.
	mu      sync.Mutex
	start   time.Time // Time corresponding to fasttime(0)
	running bool      // Is a clock updater running?
}
```

**Comment by gandarez** [comment]
I'll try to get a linux 32bit in a VM to try it out

**Comment by gandarez** [comment]
@dlclark it should work as reported in other repos https://github.com/census-instrumentation/opencensus-go/issues/587 https://github.com/p4gefau1t/trojan-go/pull/358/files https://github.com/census-instrumentation/opencensus-go/pull/588/files

**Comment by alanhamlett** [comment]
Thanks!

Looks prone to regression, if someone changes the struct order. Should there be a big blaring comment saying not to change the order in that struct?
