### ISSUE TITLE
Force timeout for testing?

### ISSUE THREAD

**Issue by jsumners** [dlclark/regexp2#62]
I'm trying to force a timeout as part of my unit testing. Unfortunately, the expression gets evaluated too quickly and never times out. Roughly, my code looks like:

https://play.golang.com/p/fuXQh3RdyuO
<details><summary>Example</summary>
<p>

```go
package main

import (
	"github.com/dlclark/regexp2"
	"testing"
	"time"
)

var regex = regexp2.MustCompile(`\d{4}-\d{2}-\d{2}`, regexp2.None)

func init() {
	regex.MatchTimeout = 1 * time.Second
}

func StringMatches(input string) (bool, error) {
	return regex.MatchString(input)
}

func TestLastIndex(t *testing.T) {
	originalTimeout := regex.MatchTimeout
	regex.MatchTimeout = -1 * time.Nanosecond

	result, err := StringMatches("2023-03-28")
	if result == true {
		t.Error("expected match false due to timeout")
	}
	if err == nil {
		t.Error("expected timeout error")
	}

	regex.MatchTimeout = originalTimeout
}
```

</p>
</details> 

The only major difference being that my regular expression is a more complicated date time string matcher with named groups.

Is there a way to force the evaluator to timeout for testing? Otherwise, I'm not sure how I can cover the error case of `MatchString`/`FindStringMatch`.

**Comment by dlclark** [comment]
There's no way to force this via the library directly. The regex in your example doesn't have any backtracking so there's basically no chance of a timeout unless you give it an enormous amount of input.  And even the engine can process gigabytes per second. I'd recommend just not setting a MatchTimeout in this case.

If you really want to have a timeout and test it like this then In your example I'd make the `StringMatches` function modal so you can set it up to sometimes return an error for testing purposes.

**Comment by jsumners** [comment]
Then there is no way to achieve 100% coverage of code that uses this library in such a situation. Basically, there should be a `MatchString` that does not return a timeout error at all.

**Comment by dlclark** [comment]
If you don't set a timeout then you can ignore the `err` param since it'll never be set: `result, _ = regex.MatchString(input)` and you'll be all set.
