### ISSUE TITLE
No support for full unicode that is supported by the ECMAScript regex

### ISSUE THREAD

**Issue by kengleong** [dlclark/regexp2#67]
```go
exp, _ := regexp2.Compile("[\u{00061}-\u{0007A}]", regexp2.ECMAScript)
_, err := exp.MatchString(val)
fmt.Println(err.Error())
```

will end up with this error message

`error parsing regexp: [}-u] range in reverse order in [\\u{0007A}-\\u{00061}]`

**Comment by dlclark** [comment]
This should work:
`exp := regexp2.MustCompile("[\\u{00061}-\\u{0007A}]", regexp2.ECMAScript|regexp2.Unicode)`

The original example doesn't work for a few reasons:

1. Go requires slashes to be escaped in double-quoted strings. `\u` will be interpreted by the compiler doesn't compile in this context. `\\u` fixes this
2. the regex `[\u{00061}-\u{0007A}]` doesn't work in basic ECMAScript.  You must enable Unicode parsing for it to work (the "u" option). This is the same in `regexp2`--you need to send `ECMAScript|Unicode` as options for this unicode character parsing to work.
