### ISSUE TITLE
xeger functionality

### ISSUE THREAD

**Issue by kmirzavaziri** [dlclark/regexp2#68]
Does this library support the `xeger` functionality? For example I have the following regex that is not supported by standard regexp library.

```
(?!((?!a(b|c)z)|(?!a(c|d)z)))
```

I need to do something like

```
r, _ := regexp2.Compile(`(?!((?!a(b|c)z)|(?!a(c|d)z)))`, 0)
s, _ := r.GenerateMatchingString()
```

I need something like this that gives me a string that matches the regex, if any exists, for example:

```
acz
```

Is this functionality already implemented? I believe Fare has this feature. (https://github.com/moodmosaic/Fare/blob/master/Src/Fare/Xeger.cs)

Can we probably use those codes to add this feature? I am willing to contribute and add this feature if it is welcome.

**Comment by dlclark** [comment]
Hello!
`regexp2` does not support generating random strings that match an input pattern. The code you linked uses a style of regex engine (state and transition) that lends itself to generating those types of strings. I suspect the opcode-with-backtracking matching method used in `regexp2` will make generating these kinds of strings more complex to implement.

You're welcome to code it up, but I think it makes more sense to maintain it as a separate library that uses the `regexp2/syntax` package for parsing the regex into opcodes.
