### ISSUE TITLE
Problems with Negative Lookahead

### ISSUE THREAD

**Issue by Nhoya** [dlclark/regexp2#7]
```
re := regexp2.MustCompile(`(?m)^.*(?!/bin/bash)$`,0)
match,_ := re.FindStringMatch(string(passwd))
```
I'm trying to take all the string execpt the ones containing /bin/bash but actually the result is just the first line of /etc/passwd that contains /bin/bash

**Comment by dlclark** [comment]
Hi Nhoya, I think it's likely that this is a problem with your pattern. I'm not able to reproduce a problem with negative lookaheads. 

Can you try your input and pattern on http://regex101.com ?

If the PCRE engine works but regexp2 doesn't then please re-open this issue and give me the pattern, input, and expected output. 

Thanks,
Doug

**Comment by Nhoya** [comment]
Here is a regex that match everything except /bin/false
https://regex101.com/r/zCKb2P/1
and here is the implementation
```
re := regexp2.MustCompile(`/^((?!\/bin\/false).)*$/m`,0)
match,_ := re.FindStringMatch(string(passwd))
```
printing `match` will return an empty string

**Comment by dlclark** [comment]
In the implementation pattern you pasted above you have `/m` at the end of the pattern text that shouldn't be there.  The `/pattern/options` syntax isn't supported by regexp2.

It should be:

```
re := regexp2.MustCompile(`^((?!\/bin\/false).)*$`, regexp2.Multiline)
match,_ := re.FindStringMatch(string(passwd))
```

If you're wanting to iterate the matches from a single input string then you'll want to do something like this:

```
re := regexp2.MustCompile(`^((?!/bin/false).)*$`, regexp2.Multiline)
for m, _ := re.FindStringMatch(string(passwd)); m != nil; m, _ = re.FindNextMatch(m) {
	fmt.Printf("match: %v\n", m)
}
```
