### ISSUE TITLE
Match loop cause high CPU usage

### ISSUE THREAD

**Issue by 0xffffharry** [dlclark/regexp2#70]
go pprof profile file:

[pprof.cdns.samples.cpu.001.pb.gz](https://github.com/dlclark/regexp2/files/13226507/pprof.cdns.samples.cpu.001.pb.gz)

**Comment by dlclark** [comment]
Can you add a bit more detail to the ticket? What are the regex pattern, input string, options being used, etc? What behavior occurred and what behavior did you expect? A short unit test to reproduce the issue would be great.

**Comment by yaotthaha** [comment]
I am looking for the regex pattern, and I will later attach it to this issue.
