### ISSUE TITLE
.Replace() wrong result with symbols $& in new content

### ISSUE THREAD

**Issue by borzovplus** [dlclark/regexp2#79]
v1.11.0

**Steps:**
var regexpOptions regexp2.RegexOptions = regexp2.Singleline | regexp2.RE2 | regexp2.Unicode
regexpObject, _ := regexp2.Compile("1", regexpOptions)
result, _ := regexpObject.Replace("1", "$&", -1, -1)

**Expected:**
result == "$&"

**Actual:**
result == "1"

**Comment by dlclark** [comment]
Hello, in regex substitutions `$&` has a special meaning--it means "the entire match" so you're replacing "1" with whatever is matched...which is "1"...so no change occurs.

You can read more about the substitutions available here:
https://learn.microsoft.com/en-us/dotnet/standard/base-types/substitutions-in-regular-expressions

If you want to literally substitute with `$&` you'll need to escape the `$` and use `$$&`.
