### ISSUE TITLE
Regex compilation breaks on certain grouping

### ISSUE THREAD

**Issue by jjngx** [dlclark/regexp2#82]
Hi, first, thanks for providing the excellent package to the community!

I have a use case where I try to compile the following regex:

```shell
~/tea/(/|$)(?P<lmatch>.*)
``` 

Unfortunately, it breaks with the following message:

```shell
panic: regexp2: Compile(`~/tea/(/|$)(?P<lmatch>.*)`): error parsing regexp: unrecognized grouping construct: (?P in `~/tea/(/|$)(?P<lmatch>.*)`
```

I use v1.11.0:

```shell
module regbug

go 1.22.5

require github.com/dlclark/regexp2 v1.11.0
```

The regex compiles successfully using Go `regexp` pkg from the std lib.

I would appreciate if you could provide information if this could be a bug.

**Comment by dlclark** [comment]
Hello, glad you’re enjoying the package!

Which options are you using to compile your pattern? Regexp2 is based on the C# engine so I maintain syntax compatibility with that by default. If you would like more compatibility with Go regexp package then you’ll want to use the RE2 option. The readme.md has more details on all the things that changes. 

The C# regex syntax for named groups is without the P: `(?<name>blah)`

**Comment by jjngx** [comment]
@dlclark thank you! all is working fine after adding the RE2 option!
