### ISSUE TITLE
regular problem

### ISSUE THREAD

**Issue by yupor5** [dlclark/regexp2#87]
"^(?<loccurtime>\d{2}\s+\d{2}\s+\d{2}:\d{2}:\d{2})\s+(?<cdevip>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})\s(?<ceventname>CisACS\_\d{2}\_\w+)\s(\w+)\s(\d+)\s(\d+)\s(?<ceventdigest>[\S\s]+)"
"03 02 00:20:23 172.1.115.1 CisACS_05_TACACSAdmin jrksb8ms 1 0 start_time=1425226823,User-Name=yybcheck.fj,Group-Name=YYB-CHECKLIST,cmd=enable <cr>,priv-lvl=0,NAS-IP-Address=172.3.3.41,"

error parsing regexp: unrecognized escape sequence \_ in `^(?<loccurtime>\d{2}\s+\d{2}\s+\d{2}:\d{2}:\d{2})\s+(?<cdevip>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})\s(?<ceventname>CisACS\_\d{2}\_\w+)\s(\w+)\s(\d+)\s(\d+)\s(?<ceventdigest>[\S\s]+)`

**Comment by dlclark** [comment]
The regex in the error has `\_` which isn’t an escape sequence. You can just use `_`. That doesn’t match the string you pasted though, so something may be getting munged in the reporting.
