### ISSUE TITLE
Incorrect \s+ Matching Non-Whitespace Bytes in Unicode Strings

### ISSUE THREAD

**Issue by StarrickLiu** [dlclark/regexp2#89]
When using the `\s+` regular expression with the `regexp2` library in Go, it incorrectly matches non-whitespace bytes within Unicode strings containing multi-byte characters. This results in invalid matches where non-whitespace characters are treated as whitespace.

**Steps to Reproduce**:

1. **Create a Go Program**:

   ```go
   package main

   import (
       "fmt"
       "github.com/dlclark/regexp2"
   )

   func main() {
       p := regexp2.MustCompile(`\s+`, regexp2.None)
       inside := "𝔾𝕠𝕠𝕕 𝕞𝕠𝕣𝕟𝕚𝕟𝕘"
       match, err := p.FindStringMatch(inside)
       if err != nil {
           fmt.Println("Error:", err)
           return
       }
       if match != nil {
           fmt.Printf("Match: %q at [%d-%d]\n", inside[match.Index:match.Index+match.Length], match.Index, match.Index+match.Length)
       } else {
           fmt.Println("No match found")
       }
   }
   ```

2. **Run the Program**:

   Ensure you have Go installed and the `regexp2` library fetched. Then execute:

   ```sh
   go run main.go
   ```

**Expected Behavior**:

The regular expression `\s+` should only match whitespace characters. In the string `"𝔾𝕠𝕠𝕕 𝕞𝕠𝕣𝕟𝕚𝕟𝕘"`, it should match the single space `" "` at byte offsets `[16-17]`.

**Actual Behavior**:

The regular expression incorrectly matches the byte `\xf0` at byte offsets `[4-5]`, which is part of the Unicode character `"𝕠"`. This leads to the following output:

```
Match: " " at [16-17]
```

However, during testing with additional debug statements, an unexpected match of `\xf0` was observed:

```
=== Debug: Starting findMatches ===
Input string: "𝔾𝕠𝕠𝕕 𝕞𝕠𝕣𝕟𝕚𝕟𝕘"
Total length (bytes): 45
byte 0: f0
byte 1: 9d
byte 2: 94
byte 3: be
byte 4: f0
byte 5: 9d
byte 6: 95
byte 7: a0
...
Match found: " " at byte offsets [16-17]
Matched segment: " " at byte offsets [16-17]
Unmatched segment at end: "𝕞𝕠𝕣𝕟𝕚𝕟𝕘" at byte offsets [17-45]
=== Debug: Completed findMatches ===
Final matches: []normalizer.OffsetsMatch{
    {Offsets: []int{0, 4}, Match:false},
    {Offsets: []int{4, 5}, Match:true},
    {Offsets: []int{5, 45}, Match:false},
}
```

**Environment**:

- **Go Version**: 1.20.5
- **regexp2 Version**: v1.11.4
- **OS**: Ubuntu 20.04

**Comment by dlclark** [comment]
`regexp2`'s match returns the index and length of the underlying _runes_ slice not the byte offset of the string. I know this is not ideal, but it's an artifact of the compatibility between the original C# engine (which uses UTF16 rune-based strings) and Go (with UTF-8 byte strings).

If you need the string that was matched you can use `match.String()` which will use the underlying rune slice and indices for you.
